# server settings
baseurl: "/"
port: 4000
encoding: utf-8

# generation settings
markdown: kramdown

compress_html:
  comments: all
  endings: all
  startings: [html, head, body]

sass:
  style: compressed

# magic strings
title: solemnsky
description: solemnsky, the open-source competitive multiplayer 2D plane game
url: "http://solemnsky.com" 
github-url: "http://github.com/solemnsky/solemnsky"

